### ISSUE TITLE
User Activity Report

### ISSUE THREAD

**Issue by WhatsNewSaes** [LeoTraining/Leo-Department-Manager#1]
How hard would it be to send a report to the department admin based on the activity of their users? (#of times logged in, downloaded materials, etc?)

**Comment by nhobi** [comment]
We'd have to make sure all the correct data is being tracked. If it isn't, we'd have to start tracking it. We'd have to know what 'etc' means. The bulk of the effort isn't in sending an automated email to ad admin, but making sure we have access to the data they want.
