### ISSUE TITLE
Send email after user registration

### ISSUE THREAD

**Issue by nhobi** [LeoTraining/Leo-Department-Manager#10]

**Comment by WhatsNewSaes** [comment]
Went back and looked at this, and it's not functioning as I'd like.

I’d like this to behave similar to the way users are currently registered on the site. It sends them a configured welcome that is editable in S2member. You can see this under S2Member > General Options > Email Configuration

This is the email that gets sent whenever I add a user through the backend. Or if someone signs up through the S2Member shortcode form that can be put on a page. 

It tells them that they’re username has been created and *they need to set their password.*

I tried to invite myself (Seth@mugwomp.com) and it added me to the list, but it didn’t email me with any details. 

- [x] Also after I added myself and then clicked the manual add button again, it was stuck on the success message from the first add. Wouldn’t go away after refresh either.

Here's the screenshot from the original specs we talked through.

<img width="1362" alt="screenshot 2017-09-14 06 50 28" src="https://user-images.githubusercontent.com/2118456/30517141-96c7a8e2-9b23-11e7-9571-2609e1a2b384.png">
