### ISSUE TITLE
Account Creation Password Screen

### ISSUE THREAD

**Issue by WhatsNewSaes** [LeoTraining/Leo-Department-Manager#18]
* There’s no reason to have any type of password strength indicator or instructions. Can we just hide with CSS?
* Can we also change `Reset Password` to `Set Password`
<img width="647" alt="screenshot 2017-09-28 21 20 18" src="https://user-images.githubusercontent.com/2118456/31017260-e332e404-a4f5-11e7-8e05-bb3612fc57a5.png">

**Comment by WhatsNewSaes** [comment]
if possible log user in after setting password

**Comment by nhobi** [comment]
![image](https://user-images.githubusercontent.com/3997403/32243770-bf468aee-be4c-11e7-92a6-43c999139740.png)
