### ISSUE TITLE
Mailchimp Sync issue

### ISSUE THREAD

**Issue by WhatsNewSaes** [LeoTraining/Leo-Department-Manager#27]
Just deactivated the department `wheeling` (on a separate note, it took about 3 tries to deactivate them, just kept churning - I got a timeout error twice)

Anyway, I went into mailchimp to see if there were any remaining wheeling officers in the admin/courtsmart grouping and found that `LCarmody@wheelingil.gov` is in both free & admin

He was the department admin for the wheeling department. I deactivated their department, and all users were correctly set to "Free Subscription" role & it looks like all normal users were moved to the `free user` mailchimp group. However `LCarmody@wheelingil.gov` remains in admin as well as free.

**Comment by nhobi** [comment]
I might need to move the department deactivation to a batch rather than marking users one by one -- for bigger depts timeout stuff is definitely a possibility here. @WhatsNewSaes

**Comment by nhobi** [comment]
Moving this to #32
